name:                weather-cli
version:             0.1.0.0
github:              "githubuser/weather-cli"
license:             BSD3
author:              "zuzia-kru"
maintainer:          "example@example.com"
copyright:           "2020 zuzia-kru"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/weather-cli#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  weather-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - weather-cli

tests:
  weather-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - weather-cli
